swapd: checkme, fixed pattern match to avoid failing unwrap
treating as if the bug is on the pop unwrap, since the expect is checked

2022-07-17T13:13:23.6366705Z [2022-07-17T13:13:23Z DEBUG microservices::esb::controller] syncer<(Monero,Local)> -> swap<0x8478…a469>: syncer_event(TransactionConfirmations(TransactionConfirmations { id: TaskId(1
1), block: [178, 67, 8, 101, 245, 54, 2, 17, 91, 42, 117, 121, 49, 102, 1, 0, 114, 0, 189, 96, 58, 32, 16, 52, 132, 231, 198, 83, 77, 42, 7, 187], confirmations: Some(20), tx: [] }))
2022-07-17T13:13:23.6368099Z thread 'main' panicked at 'Checked above', src/swapd/runtime.rs:1239:30
2022-07-17T13:13:23.6368705Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace